apiVersion: v1
kind: Pod
metadata:
  name: curl-allowed
  namespace: netpol-demo
  labels:
    app: curl
    role: frontend
spec:
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ["sleep", "3600"]
