apiVersion: batch/v1
kind: CronJob
metadata:
  name: every-minute
  namespace: jobs-demo
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: clock
              image: busybox:1.36
              command: ["sh", "-c", "date; echo Tick from CronJob"]
