apiVersion: v1
kind: Pod
metadata:
  name: kubectl-tester
  namespace: rbac-demo
spec:
  serviceAccountName: pod-reader-sa
  containers:
    - name: kubectl
      image: bitnami/kubectl:latest
      command: ["sleep", "3600"]
