# STAGE 1: Build
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

COPY HelloWorld.java .
RUN javac HelloWorld.java && jar cf app.jar HelloWorld.class

# Stage 2: Create the final distroless image
FROM gcr.io/distroless/java21-debian12
# Copy the compiled JAR from the build stage
COPY --from=build /app/*.jar /app/main.jar
WORKDIR /app
# The entrypoint is pre-configured to run 'java -jar'
CMD ["main.jar"]
